# Generated by Django 6.0.3 on 2026-04-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_rename_name_category_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quiz.quiz_question')),
            ],
        ),
    ]
