# Generated by Django 6.0.3 on 2026-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
