# Generated by Django 6.0.3 on 2026-04-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('questions', '0003_alter_question_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='catalog.category'),
        ),
    ]
